//! The embedding correctness oracle (RFC-013 Phase 1).
//!
//! Pins the vectors the engine produces against values captured from the
//! pre-tract engine (fastembed / ONNX Runtime). Its whole purpose is to catch
//! the one failure mode an engine swap has that nothing else would:
//!
//! **A wrong engine does not crash.** It returns plausible numbers, search
//! keeps working, results look like results — and are quietly meaningless.
//! There is no error to see, no test that fails on its own, no user complaint
//! until someone notices the ranking makes no sense. This file is the only
//! thing standing between that and a release.
//!
//! Fixture: `tests/fixtures/embedding_reference.json`, produced by
//! `examples/capture_embedding_reference.rs` while the old engine still
//! existed. Do not regenerate it to make a failure go away — that inverts the
//! test into a rubber stamp. Regenerate only when the model itself changes,
//! deliberately, and say so in the commit.
//!
//! Tolerance is 1e-6 per component. float32 arithmetic reorders under a
//! different runtime, so exact equality would fail for reasons that are not
//! defects; 1e-6 is far tighter than any real divergence and far looser than
//! float noise. The tract spike measured 1.6e-07 (EVID-159).
//!
//! # Where this gate actually runs — read before trusting a green CI
//!
//! **Not in CI.** This file is behind `semantic-search`, and CI builds the
//! default config, so these tests are not merely skipped there — they are not
//! compiled. CI does `cargo check --features semantic-search`, which proves
//! the code builds and nothing more.
//!
//! Running the oracle needs the 2.1 GB model, which is not worth fetching on
//! every push. So the correctness gate is **local and deliberate**: run it
//! before changing anything about tokenization, pooling, normalisation or the
//! engine itself.
//!
//!     cargo test -p forgeplan-core --features semantic-search \
//!         --test embedding_reference
//!
//! Stating this plainly because the alternative is worse: a reviewer who
//! assumes CI covers it would be relying on a gate that never fires — the
//! same shape of mistake this oracle exists to catch.

#![cfg(feature = "semantic-search")]

use std::path::PathBuf;

/// Per-component tolerance. See the module note on why not exact equality.
const TOLERANCE: f32 = 1e-6;

struct Case {
    name: String,
    text: String,
    vector: Vec<f32>,
}

struct Fixture {
    model: String,
    dim: usize,
    cases: Vec<Case>,
}

fn fixture_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/embedding_reference.json")
}

/// Minimal reader for the fixture's known shape.
///
/// Deliberately not serde: the fixture is written by hand-rolled JSON in the
/// generator, and a parser that only understands that exact shape will fail
/// loudly if the format drifts, rather than silently deserialising a
/// half-correct structure.
fn load_fixture() -> Fixture {
    let path = fixture_path();
    let raw = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "cannot read the embedding oracle at {}: {e}\n\
             It is generated by:\n  cargo run -p forgeplan-core \
             --features semantic-search --example capture_embedding_reference",
            path.display()
        )
    });

    let model = extract_string(&raw, "\"model\": \"").expect("fixture has no `model`");
    let dim: usize = extract_scalar(&raw, "\"dim\": ")
        .expect("fixture has no `dim`")
        .parse()
        .expect("`dim` is not a number");

    let mut cases = Vec::new();
    let mut rest = raw.as_str();
    while let Some(start) = rest.find("\"name\": \"") {
        rest = &rest[start..];
        let name = extract_string(rest, "\"name\": \"").expect("case has no `name`");

        let text_start = rest.find("\"text\": \"").expect("case has no `text`") + 9;
        let text_raw = read_json_string(&rest[text_start..]);

        let vec_start = rest.find("\"vector\": [").expect("case has no `vector`") + 11;
        let vec_end = rest[vec_start..].find(']').expect("unterminated `vector`");
        let vector: Vec<f32> = rest[vec_start..vec_start + vec_end]
            .split(',')
            .map(|v| v.trim().parse::<f32>().expect("vector holds a non-number"))
            .collect();

        cases.push(Case {
            name,
            text: text_raw,
            vector,
        });
        rest = &rest[vec_start + vec_end..];
    }

    Fixture { model, dim, cases }
}

fn extract_string(haystack: &str, key: &str) -> Option<String> {
    let start = haystack.find(key)? + key.len();
    Some(read_json_string(&haystack[start..]))
}

fn extract_scalar(haystack: &str, key: &str) -> Option<String> {
    let start = haystack.find(key)? + key.len();
    let end = haystack[start..].find([',', '\n'])?;
    Some(haystack[start..start + end].trim().to_string())
}

/// Read up to the closing quote, undoing the generator's escaping.
fn read_json_string(s: &str) -> String {
    let mut out = String::new();
    let mut chars = s.chars();
    while let Some(c) = chars.next() {
        match c {
            '"' => break,
            '\\' => match chars.next() {
                Some('n') => out.push('\n'),
                Some('t') => out.push('\t'),
                Some('r') => out.push('\r'),
                Some('"') => out.push('"'),
                Some('\\') => out.push('\\'),
                Some(other) => out.push(other),
                None => break,
            },
            c => out.push(c),
        }
    }
    out
}

/// Build an embedder, or explain why the gate did not run.
///
/// Returns `None` when the model is not on this machine. Deliberately loud:
/// "skipped" alone would read as "checked and fine" in a scroll-back, and this
/// is the one test whose silence is indistinguishable from success.
fn embedder_or_skip(test_name: &str) -> Option<forgeplan_core::embed::Embedder> {
    match forgeplan_core::embed::Embedder::new() {
        Ok(e) => Some(e),
        Err(err) => {
            eprintln!(
                "\n!! {test_name} DID NOT RUN — NOTHING WAS VERIFIED.\n\
                 !! The embedding model is not available on this machine:\n\
                 !!   {err}\n\
                 !! Fetch it with `forgeplan setup`, then re-run. Until then the\n\
                 !! correctness of the engine is unchecked, not confirmed.\n"
            );
            None
        }
    }
}

/// The oracle itself: every fixture case must reproduce component-for-component.
#[test]
fn embeddings_match_the_captured_reference() {
    let fixture = load_fixture();
    assert!(!fixture.cases.is_empty(), "the oracle has no cases");

    let Some(mut embedder) = embedder_or_skip("embeddings_match_the_captured_reference") else {
        return;
    };

    assert_eq!(
        embedder.model_name(),
        fixture.model,
        "the oracle was captured on a different model — comparing against it \
         would be meaningless"
    );

    let mut failures = Vec::new();

    for case in &fixture.cases {
        let actual = embedder
            .embed(&case.text)
            .unwrap_or_else(|e| panic!("case `{}` failed to embed: {e}", case.name));

        if actual.len() != case.vector.len() {
            failures.push(format!(
                "  {}: dimension {} != expected {}",
                case.name,
                actual.len(),
                case.vector.len()
            ));
            continue;
        }

        // Report the worst component rather than the first mismatch: the size
        // of the divergence says whether this is float noise or a different
        // computation, and the first component is rarely the worst one.
        let mut worst = 0.0f32;
        let mut worst_at = 0usize;
        for (i, (a, e)) in actual.iter().zip(case.vector.iter()).enumerate() {
            let d = (a - e).abs();
            if d > worst {
                worst = d;
                worst_at = i;
            }
        }

        if worst > TOLERANCE {
            failures.push(format!(
                "  {}: max deviation {:.3e} at component {} (actual {:.9}, expected {:.9})",
                case.name, worst, worst_at, actual[worst_at], case.vector[worst_at]
            ));
        }
    }

    assert!(
        failures.is_empty(),
        "the engine no longer reproduces the reference embeddings.\n\
         This is the silent-failure case: search would keep working and return \
         plausible nonsense.\n{}\n\n\
         If the model was changed deliberately, regenerate the oracle and say so \
         in the commit. Otherwise the replacement engine computes something else.",
        failures.join("\n")
    );
}

/// Dimension is an invariant of RFC-013 (#1): change it and the existing
/// LanceDB index stops being comparable, which is a data migration rather than
/// an engine swap.
#[test]
fn dimension_is_unchanged() {
    let fixture = load_fixture();
    let Some(embedder) = embedder_or_skip("dimension_is_unchanged") else {
        return;
    };

    assert_eq!(
        embedder.dim(),
        fixture.dim,
        "embedding dimension changed — the existing index is no longer comparable"
    );
}

/// The generator and the oracle must agree on what is being pinned. If a case
/// is added to `reference_cases()` without regenerating, the new case is
/// silently unverified — which looks exactly like coverage.
#[test]
fn every_declared_case_is_present_in_the_oracle() {
    let fixture = load_fixture();
    let declared = forgeplan_core::embed::reference_cases();

    let captured: Vec<&str> = fixture.cases.iter().map(|c| c.name.as_str()).collect();
    let missing: Vec<&str> = declared
        .iter()
        .map(|(name, _)| *name)
        .filter(|name| !captured.contains(name))
        .collect();

    assert!(
        missing.is_empty(),
        "these cases are declared but not captured, so nothing verifies them: {missing:?}\n\
         Regenerate with: cargo run -p forgeplan-core --features semantic-search \
         --example capture_embedding_reference"
    );
}
